# Autogenerated by ensure-dcmtk.ps1
INCLUDEPATH += C:/src/vcpkg/installed/x64-windows/include C:/src/vcpkg/installed/x64-windows/include/opencv4
LIBS += -LC:/src/vcpkg/installed/x64-windows/lib
LIBS += "C:/src/vcpkg/installed/x64-windows/lib/ofstd.lib"
LIBS += "C:/src/vcpkg/installed/x64-windows/lib/oflog.lib"
LIBS += "C:/src/vcpkg/installed/x64-windows/lib/oficonv.lib"
LIBS += "C:/src/vcpkg/installed/x64-windows/lib/dcmdata.lib"
LIBS += "C:/src/vcpkg/installed/x64-windows/lib/dcmimgle.lib"
LIBS += "C:/src/vcpkg/installed/x64-windows/lib/dcmimage.lib"
LIBS += "C:/src/vcpkg/installed/x64-windows/lib/dcmjpeg.lib"
LIBS += "C:/src/vcpkg/installed/x64-windows/lib/dcmjpls.lib"
LIBS += "C:/src/vcpkg/installed/x64-windows/lib/dcmtkcharls.lib"
DEFINES += GLIMPSE_NO_DCMRLE

